---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:12.0.2
  amd64: ghcr.io/hassio-addons/base-python/amd64:12.0.2
  armhf: ghcr.io/hassio-addons/base-python/armhf:12.0.2
  armv7: ghcr.io/hassio-addons/base-python/armv7:12.0.2
  i386: ghcr.io/hassio-addons/base-python/i386:12.0.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
args:
  DEHYDRATED_VERSION: v0.7.1
  LEXICON_VERSION: 3.17.0
  PIP_VERSION: 23.3.1
