---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:16.0.1
  amd64: ghcr.io/hassio-addons/base-python/amd64:16.0.1
  armhf: ghcr.io/hassio-addons/base-python/armhf:16.0.1
  armv7: ghcr.io/hassio-addons/base-python/armv7:16.0.1
  i386: ghcr.io/hassio-addons/base-python/i386:16.0.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
args:
  DEHYDRATED_VERSION: v0.7.1
  LEXICON_VERSION: 3.21.1
  PIP_VERSION: 24.3.1
